@include('edge-errors.layout', [
    'title' => $title ?? 'Temporarily unavailable',
    'eyebrow' => 'Temporary Disruption',
    'headline' => $headline ?? 'The site is having trouble responding right now.',
    'lede' => $lede ?? 'This usually means the origin is overloaded, restarting, timing out, or temporarily unavailable behind the edge network.',
    'domainLabel' => $domainLabel,
    'statusCode' => $statusCode,
    'steps' => [
        'Wait a minute and refresh the page once to see if service has recovered.',
        'If you manage the site, check origin health, recent deploys, and upstream service dependencies.',
        'If the issue continues, contact the site owner so they can investigate the origin response.',
    ],
    'primaryActionLabel' => 'Try again',
    'secondaryActionLabel' => 'Contact support',
    'footerNote' => $footerNote ?? 'The edge is still online and serving a branded fallback, but the origin behind this website needs attention before normal traffic can resume.',
    'sideTitle' => $sideTitle ?? 'Likely cause',
    'sideBody' => $sideBody ?? 'This status usually points to upstream instability: origin overload, maintenance windows, application crashes, or dependency timeouts before the page could complete.',
    'recoveryCopy' => $recoveryCopy ?? 'For visitors, a short wait is often enough. For site owners, check application logs, server health, recent deploys, and third-party integrations tied to the affected route.',
    'badges' => ["Status {$statusCode}", 'Edge online', 'Origin recovery needed'],
])
