<?php

return [
    'waf' => [
        'nav_label' => 'WAF',
        'eyebrow' => 'Managed Edge Firewall',
        'title' => 'WordPress-focused WAF protection without the usual security noise.',
        'description' => 'FirePhage stops hostile traffic at the edge before it reaches your origin. Teams see clear attack summaries, practical recommendations, and a dashboard built for humans instead of firewall specialists.',
        'summary' => 'Managed WAF for WordPress, WooCommerce, Laravel, APIs, and agency portfolios.',
        'seo_title' => 'WordPress WAF Protection | FirePhage',
        'seo_description' => 'Managed WordPress WAF protection from FirePhage. Stop hostile traffic at the edge, reduce origin pressure, and see clear attack visibility in one dashboard.',
        'problem' => 'A typical website owner does not need a giant firewall rule maze. They need clear protection, readable alerts, and help when traffic turns hostile.',
        'image' => 'dashboard-preview.webp',
        'image_alt' => 'FirePhage dashboard preview',
        'proof' => [
            ['label' => 'Attack filtering', 'value' => '99.9%'],
            ['label' => 'Daily visibility', 'value' => '24/7'],
            ['label' => 'Human-readable alerts', 'value' => 'Built in'],
        ],
        'outcomes' => [
            ['title' => 'Stop noisy attack traffic early', 'body' => 'Malicious requests are handled at the edge so your origin does less defensive work under pressure.'],
            ['title' => 'Understand what was blocked', 'body' => 'See readable attack summaries, action types, countries, and hot paths without digging through raw logs.'],
            ['title' => 'Move faster during incidents', 'body' => 'When a site comes under pressure, your team gets a calm operational picture instead of fragmented security noise.'],
        ],
        'feature_cards' => [
            ['title' => 'Managed rule posture', 'body' => 'Protection modes are tuned for real websites, not left as a blank firewall project for your team to solve.'],
            ['title' => 'Origin shielding', 'body' => 'Requests are evaluated before they touch your infrastructure, helping reduce direct exposure to the origin.'],
            ['title' => 'Readable threat telemetry', 'body' => 'Blocked attack counts, recent events, and protection state are visible in one place.'],
            ['title' => 'Agency-ready oversight', 'body' => 'Teams managing multiple domains get one dashboard instead of disconnected edge tools.'],
        ],
        'example' => [
            'title' => 'Example: login attack spike',
            'body' => 'A WordPress login endpoint starts receiving a burst of hostile POST requests from multiple countries. FirePhage blocks or challenges that traffic at the edge, shows the affected paths, and helps the team see whether the attack is widening or calming down.',
        ],
        'graph' => [
            'title' => 'Blocked requests trend',
            'points' => [18, 26, 22, 41, 64, 52, 88, 57, 34, 21],
        ],
    ],
    'cdn' => [
        'nav_label' => 'CDN',
        'eyebrow' => 'Global Delivery',
        'title' => 'Global CDN delivery that improves speed without making the edge harder to manage.',
        'description' => 'FirePhage places your website closer to visitors while keeping delivery, protection, and onboarding in one product. Teams get a faster site and a clearer picture of how traffic moves through the edge.',
        'summary' => 'Global edge delivery for websites that need both speed and operational clarity.',
        'seo_title' => 'CDN for WordPress and WooCommerce | FirePhage',
        'seo_description' => 'FirePhage CDN improves website delivery with edge caching, lower origin pressure, and unified visibility for WordPress, WooCommerce, and high-traffic sites.',
        'problem' => 'Many teams want CDN performance but end up with another control panel, another layer of settings, and less visibility into what is actually happening.',
        'image' => 'hero-banner-new.png',
        'image_alt' => 'Global edge traffic illustration',
        'proof' => [
            ['label' => 'Global reach', 'value' => 'Edge-first'],
            ['label' => 'Faster delivery', 'value' => 'Lower latency'],
            ['label' => 'Operational clarity', 'value' => 'Unified'],
        ],
        'outcomes' => [
            ['title' => 'Serve visitors from the edge', 'body' => 'Static and cacheable content is delivered closer to end users instead of forcing every request back to origin.'],
            ['title' => 'Reduce origin pressure', 'body' => 'More delivery work happens at the edge, helping origin infrastructure stay calmer during busy periods.'],
            ['title' => 'Keep delivery visible', 'body' => 'Teams can see traffic and performance context in the same product used for protection and monitoring.'],
        ],
        'feature_cards' => [
            ['title' => 'Unified delivery layer', 'body' => 'CDN, protection, and site onboarding live together instead of being spread across unrelated tools.'],
            ['title' => 'Traffic-aware visibility', 'body' => 'See request volume and edge behavior through the same operational lens as protection.'],
            ['title' => 'Agency-friendly deployment', 'body' => 'Managed cutover help lowers the chance of downtime during DNS changes and site onboarding.'],
            ['title' => 'Cleaner troubleshooting', 'body' => 'Development and troubleshooting modes help teams inspect delivery behavior when a site needs attention.'],
        ],
        'example' => [
            'title' => 'Example: campaign traffic burst',
            'body' => 'A launch campaign sends a sudden spike of anonymous traffic. FirePhage serves more of that traffic from the edge, reducing origin strain while the team still sees how traffic is distributed.',
        ],
        'graph' => [
            'title' => 'Regional delivery share',
            'points' => [42, 55, 47, 63, 58, 71, 68, 74, 70, 78],
        ],
    ],
    'cache' => [
        'nav_label' => 'Cache',
        'eyebrow' => 'Cache Efficiency',
        'title' => 'Cache controls that improve performance without turning every page into a manual rule exercise.',
        'description' => 'FirePhage helps teams improve delivery efficiency while keeping cache behavior understandable. Instead of juggling scattered cache rules, you get a simpler operational view of what is cached, what is bypassed, and what still needs origin work.',
        'summary' => 'Practical cache visibility and edge controls for production websites.',
        'seo_title' => 'Website Cache Controls and Edge Efficiency | FirePhage',
        'seo_description' => 'Improve cache efficiency with FirePhage edge controls, cache visibility, and safer production workflows for dynamic WordPress and WooCommerce sites.',
        'problem' => 'Caching often becomes fragile because teams know they need it, but they do not trust what it will break. They need clear rules and readable behavior, not a maze.',
        'image' => 'dns-cutover-ui.png',
        'image_alt' => 'FirePhage interface illustration',
        'proof' => [
            ['label' => 'Cache clarity', 'value' => 'Readable'],
            ['label' => 'Origin offload', 'value' => 'Higher'],
            ['label' => 'Operational risk', 'value' => 'Lower'],
        ],
        'outcomes' => [
            ['title' => 'Make cache behavior visible', 'body' => 'Understand what the edge is doing instead of guessing whether caching is helping or hurting.'],
            ['title' => 'Lower repeat-load pressure', 'body' => 'More repeat traffic can be served efficiently from the edge rather than repeatedly hitting origin.'],
            ['title' => 'Support safer production changes', 'body' => 'Development-mode workflows make it easier to inspect changes when cache behavior needs review.'],
        ],
        'feature_cards' => [
            ['title' => 'Readable cache context', 'body' => 'Teams see cache efficiency and request handling in a way that supports real operations.'],
            ['title' => 'Origin-aware defaults', 'body' => 'Cache posture is designed to work with dynamic websites, not only static brochure sites.'],
            ['title' => 'WooCommerce-safe thinking', 'body' => 'Checkout and cart-sensitive patterns can be kept out of risky blanket caching assumptions.'],
            ['title' => 'One operational surface', 'body' => 'Cache visibility stays tied to traffic, protection, and site status.'],
        ],
        'example' => [
            'title' => 'Example: busy content site',
            'body' => 'A blog and docs-heavy website is seeing repeat anonymous traffic but still leaning too hard on origin. FirePhage highlights cache efficiency so the team can improve offload without turning the site into a brittle rule puzzle.',
        ],
        'graph' => [
            'title' => 'Cache efficiency trend',
            'points' => [22, 28, 35, 41, 47, 56, 61, 66, 72, 76],
        ],
    ],
    'ddos-protection' => [
        'nav_label' => 'DDoS',
        'eyebrow' => 'Traffic Pressure Control',
        'title' => 'DDoS-oriented edge protection that helps teams stay calm when traffic gets aggressive.',
        'description' => 'FirePhage helps reduce direct pressure on origin during disruptive traffic events and shows teams what is happening in plain language. The goal is not just mitigation, but operational clarity while traffic is hostile or unstable.',
        'summary' => 'Edge-first traffic pressure handling with understandable visibility.',
        'seo_title' => 'DDoS Protection for WordPress and High-Traffic Sites | FirePhage',
        'seo_description' => 'Edge-first DDoS protection from FirePhage helps absorb hostile traffic, reduce origin pressure, and give teams readable incident visibility during attack conditions.',
        'problem' => 'Traffic floods create two problems at once: infrastructure pressure and operator confusion. Teams need both mitigation and a readable picture of what changed.',
        'image' => 'world-map-security.png',
        'image_alt' => 'Global security traffic map',
        'proof' => [
            ['label' => 'Pressure handling', 'value' => 'Edge-first'],
            ['label' => 'Incident clarity', 'value' => 'Human-readable'],
            ['label' => 'Origin exposure', 'value' => 'Reduced'],
        ],
        'outcomes' => [
            ['title' => 'Absorb traffic earlier', 'body' => 'Suspicious surges are handled closer to the edge before they fully translate into origin pain.'],
            ['title' => 'See what changed quickly', 'body' => 'Teams can identify attack pressure, affected paths, and live protection status without raw-event overload.'],
            ['title' => 'Reduce incident guesswork', 'body' => 'The dashboard gives a practical overview while teams decide what to do next.'],
        ],
        'feature_cards' => [
            ['title' => 'Under-attack posture', 'body' => 'Sites can shift into a more defensive protection state when traffic becomes more hostile.'],
            ['title' => 'Recent event visibility', 'body' => 'Operators see fresh traffic decisions instead of waiting on vague status pages.'],
            ['title' => 'Support during onboarding', 'body' => 'FirePhage can help teams complete cutover safely before the next traffic event arrives.'],
            ['title' => 'Shared operational language', 'body' => 'Non-specialists can still understand the dashboard during stressful traffic incidents.'],
        ],
        'example' => [
            'title' => 'Example: sudden surge from noisy sources',
            'body' => 'A campaign site starts seeing a sharp, hostile request spike from multiple regions. FirePhage helps contain the pressure at the edge and shows whether the surge is concentrated on one route or moving across the site.',
        ],
        'graph' => [
            'title' => 'Pressure mitigation view',
            'points' => [15, 34, 67, 88, 93, 82, 61, 48, 36, 24],
        ],
    ],
    'bot-protection' => [
        'nav_label' => 'Bot Protection',
        'eyebrow' => 'Bot & Abuse Control',
        'title' => 'Bot protection for teams tired of noisy traffic, scripted abuse, and login pressure.',
        'description' => 'FirePhage helps block, challenge, and explain bad bot behavior across websites that need practical abuse control. That includes brute-force patterns, scripted login abuse, and noisy traffic that wastes origin resources.',
        'summary' => 'Readable bot and brute-force protection for WordPress and beyond.',
        'seo_title' => 'Bot Protection for WordPress and WooCommerce | FirePhage',
        'seo_description' => 'Stop login abuse, scraping, and scripted bot traffic with FirePhage bot protection for WordPress, WooCommerce, and other production websites.',
        'problem' => 'Bots create hidden cost even when they do not fully take a site down. They waste origin capacity, distort traffic, and create noise that site owners often struggle to interpret.',
        'image' => 'core-capabilities-illustration.svg',
        'image_alt' => 'Edge capability illustration',
        'proof' => [
            ['label' => 'Bot pressure visibility', 'value' => 'Live'],
            ['label' => 'Login abuse control', 'value' => 'Built in'],
            ['label' => 'Team clarity', 'value' => 'High'],
        ],
        'outcomes' => [
            ['title' => 'Reduce automated abuse', 'body' => 'Bad bot traffic can be blocked or challenged before it burns through origin resources.'],
            ['title' => 'Protect login surfaces', 'body' => 'Scripted login pressure and repetitive hostile requests become easier to identify and handle.'],
            ['title' => 'Keep real traffic clearer', 'body' => 'The dashboard helps separate hostile automation from real user demand.'],
        ],
        'feature_cards' => [
            ['title' => 'Brute-force visibility', 'body' => 'Understand when login endpoints are attracting hostile automated attention.'],
            ['title' => 'Challenge and block context', 'body' => 'See how the edge is responding to noisy requests instead of only seeing server strain later.'],
            ['title' => 'Bot pressure metrics', 'body' => 'Operators get a readable signal for how much hostile automation is pushing on the site.'],
            ['title' => 'WordPress-friendly posture', 'body' => 'FirePhage is designed with common WordPress attack patterns in mind.'],
        ],
        'example' => [
            'title' => 'Example: wp-login and xmlrpc noise',
            'body' => 'A WooCommerce store sees repeated hostile hits against login and XML-RPC surfaces. FirePhage reduces the pressure at the edge and gives the operator a cleaner picture of what is being blocked or challenged.',
        ],
        'graph' => [
            'title' => 'Bot pressure trend',
            'points' => [12, 19, 33, 46, 58, 63, 49, 39, 27, 18],
        ],
    ],
    'wordpress-plugin' => [
        'nav_label' => 'WordPress Plugin',
        'eyebrow' => 'WordPress Plugin',
        'title' => 'A WordPress plugin that brings local security signals into the FirePhage dashboard.',
        'description' => 'The FirePhage WordPress plugin connects local WordPress health and malware scan visibility with the hosted FirePhage dashboard. Paid sites can also pull live firewall and performance telemetry back into the WordPress admin.',
        'summary' => 'WordPress health, malware, and paid dashboard telemetry in one workflow.',
        'seo_title' => 'WordPress Security Plugin with Edge Visibility | FirePhage',
        'seo_description' => 'The FirePhage WordPress plugin connects malware, health, and local security signals into the FirePhage dashboard and paid edge telemetry workflow.',
        'problem' => 'WordPress teams often split visibility across local plugins, separate dashboards, and unreadable edge tools. They need one clearer flow.',
        'image' => 'wordpress-menu.png',
        'image_alt' => 'FirePhage WordPress plugin interface',
        'proof' => [
            ['label' => 'Health checks', 'value' => 'Connected'],
            ['label' => 'Malware results', 'value' => 'Reported'],
            ['label' => 'Paid telemetry', 'value' => 'Synced'],
        ],
        'outcomes' => [
            ['title' => 'See local WordPress signals centrally', 'body' => 'Health status, update posture, and malware scan results can be stored and reviewed in FirePhage.'],
            ['title' => 'Unlock live plugin telemetry for paid sites', 'body' => 'Covered paid sites can view live firewall and performance context directly in the plugin.'],
            ['title' => 'Connect without messy setup', 'body' => 'The plugin uses a scoped connection flow so dashboard sync is explicit and site-aware.'],
        ],
        'feature_cards' => [
            ['title' => 'Health summaries', 'body' => 'WordPress posture, checksum state, and update exposure can be reported into the SaaS dashboard.'],
            ['title' => 'Malware scan visibility', 'body' => 'Latest findings and suspicious-file counts are stored as part of the connected site view.'],
            ['title' => 'Paid firewall visibility', 'body' => 'When a site is covered by a paid plan, the plugin can load real firewall activity and performance summaries from FirePhage.'],
            ['title' => 'Agency-friendly workflow', 'body' => 'Teams can manage the site in WordPress while still using FirePhage as the main edge-control dashboard.'],
        ],
        'example' => [
            'title' => 'Example: one site, two visibility layers',
            'body' => 'A WordPress operator sees local scan findings and health checks in the plugin while the SaaS dashboard stores the same security context and adds edge-side firewall visibility for paid coverage.',
        ],
        'graph' => [
            'title' => 'Connected signal flow',
            'points' => [18, 24, 31, 44, 58, 67, 73, 79, 84, 91],
        ],
    ],
    'uptime-monitor' => [
        'nav_label' => 'Uptime Monitor',
        'eyebrow' => 'Availability Monitoring',
        'title' => 'Uptime monitoring that helps teams see service health before customers start reporting problems.',
        'description' => 'FirePhage tracks availability so teams can see service state, recent checks, and health changes in the same environment used for protection and onboarding. It is built for operators who want fewer blind spots, not another disconnected monitor tab.',
        'summary' => 'Availability visibility tied directly to site onboarding and protection state.',
        'seo_title' => 'Website Uptime Monitoring and Availability Checks | FirePhage',
        'seo_description' => 'Track website uptime and recent availability checks with FirePhage monitoring, tied directly to edge protection, onboarding, and site operations.',
        'problem' => 'Teams often discover availability issues too late, or only after jumping between multiple dashboards that do not match the rest of their operational workflow.',
        'image' => 'dashboard-preview.png',
        'image_alt' => 'FirePhage dashboard availability monitoring preview',
        'proof' => [
            ['label' => 'Recent checks', 'value' => 'Visible'],
            ['label' => 'Operational context', 'value' => 'Unified'],
            ['label' => 'Alert readiness', 'value' => 'Actionable'],
        ],
        'outcomes' => [
            ['title' => 'See recent checks in context', 'body' => 'Availability data sits next to protection, billing, and onboarding state rather than living in a separate silo.'],
            ['title' => 'Spot failures earlier', 'body' => 'Teams can review recent check results and service posture before incidents become customer-facing confusion.'],
            ['title' => 'Understand operational state faster', 'body' => 'Availability becomes part of the same product story as edge delivery and protection.'],
        ],
        'feature_cards' => [
            ['title' => 'Recent checks table', 'body' => 'Operators can review what was checked, when it was checked, and whether the site was up or down.'],
            ['title' => 'Manual checks when needed', 'body' => 'Teams can trigger checks directly when validating site state or recent changes.'],
            ['title' => 'One dashboard view', 'body' => 'Availability is not detached from the rest of the site lifecycle inside FirePhage.'],
            ['title' => 'Useful alert direction', 'body' => 'The monitoring layer fits naturally with the alerting model already built into FirePhage.'],
        ],
        'example' => [
            'title' => 'Example: checkout complaint before sales drop',
            'body' => 'A store owner hears that the site felt unstable. FirePhage check history helps the team confirm whether there was an actual availability issue and when it started.',
        ],
        'graph' => [
            'title' => 'Availability stability view',
            'points' => [96, 97, 99, 98, 97, 99, 100, 99, 100, 100],
        ],
    ],
];
